### ISSUE TITLE
[CHORE] 주문 현황에 대해 수정이 필요해 보임

### ISSUE THREAD

**Issue by bbangHo** [Capstone-Design-A/back#51]
![image](https://github.com/Capstone-Design-A/back/assets/63041700/944b5cad-3c7b-4a05-9041-3e04f5c047b0)
![image](https://github.com/Capstone-Design-A/back/assets/63041700/347ae667-1a50-4f61-ae79-f268a8dd3767)
- erd 구조를 보면 Order에 status 속성이 있는데, 실제로는 각 Order_Item 마다 상태가 붙어야함(밑에 이미지)
- 구조 변경이 필요해보임
    1. order와 order_item 모두 status를 가진다
    2. order_item만 status를 가진다.

**Comment by seongsiyoung** [comment]
OrderItem에만 status를 가지는게 좋지 않을까요??
 - Order속성이랑 OrderItem을 그냥 합치는 것도 생각해봤는데 그럼 배송비를 계산할때 Order속성이 필요해 보이네요! 
 어떻게 생각하세요??
